name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Version (like v1.0.0)
      prerelease:
        type: boolean
        required: true
        description: Prerelease or not

env:
  BUILD_TYPE: Release
  DOTNET_VERSION: 8
  ASSEMBLY_NAME: Hosihikari.FastElfQuery

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}.0.x

      - name: Build
        run: dotnet publish -c ${{env.BUILD_TYPE}}

      - name: Publish NuGet
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: src/${{env.ASSEMBLY_NAME}}.csproj
          VERSION_STATIC: ${{ github.event.inputs.version }}
          TAG_COMMIT: false
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          NO_BUILD: true

      - name: Create New Release
        uses: ncipollo/release-action@v1.14.0
        with:
          prerelease: ${{ github.event.inputs.prerelease }}
          tag: ${{ github.event.inputs.version }}
          artifacts: src/bin/Release/net${{env.DOTNET_VERSION}}.0/publish/${{env.ASSEMBLY_NAME}}.dll
